name = "dp1-feed-operator-api-dev"
main = "index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Variables for all environments
[vars]
ENVIRONMENT = "development"
SELF_HOSTED_DOMAINS = "dp1-feed-operator-api-dev.autonomy-system.workers.dev,localhost:8787"

# KV namespace bindings for storing JSON data
[[kv_namespaces]]
binding = "DP1_PLAYLISTS"
id = "4f76b8ce88854022b9bf80da15b2de34"
preview_id = "4f76b8ce88854022b9bf80da15b2de34"

[[kv_namespaces]]
binding = "DP1_PLAYLIST_GROUPS"
id = "be9799c62f3e48528d9ad51516b7f7a5"
preview_id = "be9799c62f3e48528d9ad51516b7f7a5"

[[kv_namespaces]]
binding = "DP1_PLAYLIST_ITEMS"
id = "75d25c68e4ee4284abdc97468eca122a"
preview_id = "75d25c68e4ee4284abdc97468eca122a"

# Production environment
[env.production]
name = "dp1-feed-operator-api-prod"
route = { pattern = "api.feed.feralfile.com/*", zone_name = "feralfile.com" }
[env.production.vars]
ENVIRONMENT = "production"
SELF_HOSTED_DOMAINS = "api.feed.feralfile.com, dp1-feed-operator-api-prod.autonomy-system.workers.dev"

# Production KV namespaces
[[env.production.kv_namespaces]]
binding = "DP1_PLAYLISTS"
id = "DP1_PLAYLISTS"

[[env.production.kv_namespaces]]
binding = "DP1_PLAYLIST_GROUPS"
id = "DP1_PLAYLIST_GROUPS"

[[env.production.kv_namespaces]]
binding = "DP1_PLAYLIST_ITEMS"
id = "DP1_PLAYLIST_ITEMS"

# Durable Objects (for real-time features - optional)
# [[durable_objects.bindings]]
# name = "PLAYLIST_SESSIONS"
# class_name = "PlaylistSession"

# AI binding (for future AI features - optional)
# [ai]
# binding = "AI"

# Analytics Engine (for usage tracking - optional)
# [[analytics_engine_datasets]]
# binding = "DP1_ANALYTICS"

# Rate limiting configuration
[limits]
cpu_ms = 30000

# Build configuration
[build]
command = "npm run build:worker"

# Secrets (set via wrangler secret put)
# API_SECRET - Bearer token secret
# ED25519_PRIVATE_KEY - Server signing key (REQUIRED)
# IPFS_GATEWAY_TOKEN - IPFS access token (optional) 