name: Deploy Server

on:
  push:
    branches: [main]
    paths: ['prototype/server/**']
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers

    defaults:
      run:
        working-directory: ./prototype/server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'prototype/server/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build:worker

      - name: Deploy to Cloudflare Workers (Development)
        if: ${{ github.event.inputs.environment == 'development' || github.event.inputs.environment == '' }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: './prototype/server'
          command: deploy

      - name: Deploy to Cloudflare Workers (Production)
        if: ${{ github.event.inputs.environment == 'production' }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: './prototype/server'
          command: deploy --env production
